### ISSUE TITLE
Using "extra" parameter in CreateEndSessionUrl

### ISSUE THREAD

**Issue by epuio** [IdentityModel/IdentityModel#442]
I'm new to C#. I'm attempting to get logout working with AWS Cognito. They require `client_id` and `logout_uri` as query parameters. I'm trying to use the `extra` parameter but getting a "Parameter count mismatch" error. Here is my code:

`StringDictionary cognitoParameters = new StringDictionary();
cognitoParameters.Add("client_id", OAuthConfiguration.ClientId);
cognitoParameters.Add("logout_uri", OAuthConfiguration.EndsessionEndpointPath);

var endsessionEndpoint = OAuthConfiguration.Authority.TrimEnd('/') + "/" + OAuthConfiguration.EndsessionEndpointPath;
var requestUrl = new RequestUrl(endsessionEndpoint);
var endSessionUrl = requestUrl.CreateEndSessionUrl(
    idTokenHint: HttpContext.Current.GetToken(OidcConstants.ResponseTypes.IdToken),
    postLogoutRedirectUri: OAuthConfiguration.Host,
    state: null,
    extra: cognitoParameters
);
`

Here's the full error I'm getting:

`Exception type: System.Reflection.TargetParameterCountException
Stack trace:
at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
at IdentityModel.Internal.ValuesHelper.ObjectToDictionary(Object values)
at IdentityModel.Client.RequestUrlExtensions.CreateEndSessionUrl(RequestUrl request, String idTokenHint, String postLogoutRedirectUri, String state, Object extra)
at Indice.Kentico.Oidc.EndSessionOidcHandler.EndSession()
at Indice.Kentico.Oidc.EndSessionOidcHandler.ProcessRequest(HttpContext context)
at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)`

Sorry for the newbie question. IdentityModel has been very helpful. Can you please help me format the `extra` parameter properly? I actually don't need the other parameters (since Cognito doesn't use them for logout)

**Comment by epuio** [comment]
I figured out that I needed to create a Dictionary instead of a StringDictionary:

`IDictionary cognitoParameters = new Dictionary<string,string>() {
  { "client_id", OAuthConfiguration.ClientId },
  { "logout_uri", OAuthConfiguration.Host.TrimEnd('/') + "/SignOut.ashx" }
};`

It is working now.
